blueprint:
  name: Toggle All Lights in Area with Brightness Control
  description: Toggle all lights in a specified area. If at least one light is on, turn them all off; otherwise, turn them all on with a specified brightness.
  domain: script
  input:
    target_area:
      name: Target Area
      description: The area containing the lights to toggle.
      selector:
        area: {}
    brightness:
      name: Brightness
      description: Brightness level to set when turning on the lights (0-255).
      default: 255
      selector:
        number:
          min: 0
          max: 255
          unit_of_measurement: ""
          mode: slider
variables:
  area_entities: !input target_area
sequence:
  - variables:
      lights: >
        {{ expand(area_entities) | selectattr('domain', 'eq', 'light') | map(attribute='entity_id') | list }}
      lights_on: >
        {{ expand(lights) | selectattr('state', 'eq', 'on') | list }}
  - choose:
      - conditions: "{{ lights_on | length > 0 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ lights }}"
      - conditions: "{{ lights_on | length == 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ lights }}"
            data:
              brightness: !input brightness
mode: single
