blueprint:
  name: Toggle All Lights in Area
  description: Toggle all lights in a specified area
  domain: script
  input:
    target_area:
      name: Target Area
      description: The area containing the lights to toggle.
      selector:
        area: {}
variables:
  area_entities: !input target_area
sequence:
  - variables:
      lights: >
        {{ expand(area_entities) | selectattr('domain', 'eq', 'light') | map(attribute='entity_id') | list }}
      lights_on: >
        {{ expand(lights) | selectattr('state', 'eq', 'on') | list }}
  - choose:
      - conditions: "{{ lights_on | length > 0 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ lights }}"
      - conditions: "{{ lights_on | length == 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ lights }}"
mode: single
